services:
  postgres:
    image: postgres:15-alpine
    container_name: calisat-db-inventario
    environment:
      POSTGRES_DB: calisat_inventario
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - calisat_inventario_data:/var/lib/postgresql/data
    networks:
      - calisat-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d calisat_inventario"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: calisat-ms-inventario
    ports:
      - "8083:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - calisat-net

networks:
  calisat-net:
    driver: bridge

volumes:
  calisat_inventario_data:
